name: Android
on: [push,workflow_dispatch]
jobs:
  build:
    name: NDK-Build
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: true
      - uses: actions/checkout@v4
      - name: Build
        run: |
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: VKGL
          path: libs/*

